/* HOUSE OF GEMINI — removable hidden book hunt. Edit the CONFIG to personalize. */
(()=>{"use strict";
const CONFIG={storageKey:"houseOfGeminiBookHuntV1",triggerClicks:3,revealTitle:"The book is yours.",revealMessage:"You found every hidden golden stitch in the House of Gemini. Claim your book from the person who tucked this little adventure into your website — with love."};
const clues={
1:{kicker:"A loose thread",title:"You found something that was not meant for everyone.",copy:"Three golden stitches have been hidden inside this House. Follow them in order and a small prize will reveal itself.",clue:"Every house has a beginning. Find the page where its founder tells her story.",link:"about.html",label:"Follow the thread"},
2:{kicker:"First stitch found · 1 of 3",title:"A story always leaves a clue.",copy:"The first stitch is yours. The next one is hiding somewhere brighter.",clue:"Go where the savannah blooms — among confident colour, graceful shape and timeless African style.",link:"collections.html#savannah-bloom",label:"Find where it blooms"},
3:{kicker:"Second stitch found · 2 of 3",title:"Only one stitch remains.",copy:"You are close now. The final thread begins exactly where every beautiful project begins.",clue:"Ideas become real through a process. Find its very first step: the moment someone simply tells us what they need.",link:"process.html",label:"Begin at the beginning"},
4:{kicker:"The hidden book hunt · Complete",title:CONFIG.revealTitle,copy:CONFIG.revealMessage,clue:"Proof of victory: show this screen to the one who challenged you. No loopholes. No appeals. The reader wins.",link:null,label:"Close and claim it"}};
const read=()=>{try{return Math.min(4,Math.max(0,Number(localStorage.getItem(CONFIG.storageKey))||0))}catch{return 0}},write=n=>{try{localStorage.setItem(CONFIG.storageKey,String(n))}catch{}};
let stage=read(),clicks=0,lastFocused=null;
const overlay=document.createElement("div");overlay.className="book-hunt-overlay";overlay.setAttribute("role","dialog");overlay.setAttribute("aria-modal","true");overlay.setAttribute("aria-labelledby","book-hunt-title");overlay.innerHTML='<div class="book-hunt-card"></div>';document.body.append(overlay);const card=overlay.firstElementChild;
const progress=n=>`<div class="book-hunt-progress" aria-label="${Math.max(0,n-1)} of 3 stitches found">${[2,3,4].map(x=>`<i class="${n>=x?"is-found":""}"></i>`).join("")}</div>`;
const celebrate=()=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const s=["✦","✧","♥","◆","📖"],c=["#b88b45","#d8b56d","#f7efe0","#2f6b58"];for(let i=0;i<42;i++){const p=document.createElement("span");p.className="book-hunt-confetti";p.textContent=s[i%s.length];p.style.setProperty("--x",`${Math.random()*100}vw`);p.style.setProperty("--color",c[i%c.length]);p.style.setProperty("--size",`${10+Math.random()*12}px`);p.style.setProperty("--drift",`${-70+Math.random()*140}px`);p.style.setProperty("--duration",`${3.2+Math.random()*2.4}s`);p.style.animationDelay=`${Math.random()*.7}s`;document.body.append(p);p.addEventListener("animationend",()=>p.remove())}};
const close=()=>{overlay.classList.remove("is-open");document.body.classList.remove("modal-open");lastFocused?.focus?.()};
const show=(n=stage)=>{const q=clues[n];if(!q)return;lastFocused=document.activeElement;card.innerHTML=`<button class="book-hunt-close" type="button" aria-label="Close the clue">&times;</button><div class="book-hunt-sigil" aria-hidden="true">${n===4?"📖":"✦"}</div><p class="book-hunt-kicker">${q.kicker}</p><h2 id="book-hunt-title">${q.title}</h2><p class="book-hunt-copy">${q.copy}</p><p class="book-hunt-clue">${q.clue}</p>${progress(n)}${q.link?`<a class="book-hunt-action" href="${q.link}">${q.label}</a>`:`<button class="book-hunt-action" type="button" data-book-close>${q.label}</button><button class="book-hunt-reset" type="button">Reset the hunt</button>`}`;overlay.classList.add("is-open");document.body.classList.add("modal-open");card.querySelector(".book-hunt-close").focus();card.querySelector(".book-hunt-close").onclick=close;card.querySelector("[data-book-close]")?.addEventListener("click",close);card.querySelector(".book-hunt-reset")?.addEventListener("click",()=>{write(0);stage=0;close();document.querySelector(".book-hunt-compass")?.remove()});if(n===4)celebrate()};
const compass=()=>{if(stage<1||document.querySelector(".book-hunt-compass"))return;const b=document.createElement("button");b.className="book-hunt-compass";b.type="button";b.innerHTML=`<span aria-hidden="true">✦</span><span>${stage===4?"Book found":`${Math.max(0,stage-1)} / 3 stitches`}</span>`;b.setAttribute("aria-label","Open your current book hunt clue");b.onclick=()=>show();document.body.append(b)};
const advance=n=>{stage=n;write(n);document.querySelector(".book-hunt-marker")?.remove();document.querySelector(".book-hunt-compass")?.remove();compass();show()};
const marker=(selector,next,label)=>{const target=document.querySelector(selector);if(!target)return;const b=document.createElement("button");b.className="book-hunt-marker";b.type="button";b.innerHTML="✦";b.setAttribute("aria-label",label);b.onclick=()=>advance(next);target.append(b)};
const region=document.querySelector(".footer-region");if(region){const b=document.createElement("button");b.className="book-hunt-trigger";b.type="button";b.innerHTML="✦";b.setAttribute("aria-label","A loose golden thread");b.title="Something is tucked into this seam";b.onclick=()=>{clicks++;b.style.color=`rgba(216,181,109,${Math.min(.9,.18+clicks*.22)})`;if(clicks>=CONFIG.triggerClicks){clicks=0;if(stage===0){stage=1;write(stage);compass()}show()}};region.insertAdjacentElement("afterend",b)}
compass();if(stage===1)marker(".founder-note",2,"Collect the first golden stitch");if(stage===2)marker("#savannah-bloom .collection-copy",3,"Collect the second golden stitch");if(stage===3)marker(".timeline .step:first-child",4,"Collect the final golden stitch");overlay.onclick=e=>{if(e.target===overlay)close()};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&overlay.classList.contains("is-open"))close()});
})();
